spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/apiproject}
spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.threads.virtual.enabled=true
server.port=${PORT:8080}

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.default_batch_fetch_size=50
spring.jpa.properties.hibernate.jdbc.batch_size=50
spring.jpa.properties.hibernate.order_inserts=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

jwt.expiration-ms=${JWT_EXPIRATION_MS:86400000}
jwt.secret.key=${JWT_SECRET_KEY}
cors.allowed-origin=${URL_FOR_REQUESTING_AND_RESPONSIVES:http://localhost:3000}

spring.data.web.pageable.serialization-mode=via_dto

spring.servlet.multipart.max-file-size=30MB
spring.servlet.multipart.max-request-size=30MB

spring.security.user.name=${BASIC_AUTH_USERNAME}
spring.security.user.password=${BASIC_AUTH_PASSWORD}

cloudinary.cloud-name=${CLOUDINARY_CLOUD_NAME}
cloudinary.api-key=${CLOUDINARY_API_KEY}
cloudinary.api-secret=${CLOUDINARY_API_SECRET}

springdoc.api-docs.enabled=true
spring.jpa.hibernate.ddl-auto=validate

springdoc.swagger-ui.enabled=true
springdoc.swagger-ui.path=/swagger-ui.html

# Registration para ADMIN
spring.security.oauth2.client.registration.google-admin.client-id=${GOOGLE_CLIENT_ID}
spring.security.oauth2.client.registration.google-admin.client-secret=${GOOGLE_CLIENT_SECRET}
spring.security.oauth2.client.registration.google-admin.scope=openid,email,profile
spring.security.oauth2.client.registration.google-admin.provider=google
spring.security.oauth2.client.registration.google-admin.redirect-uri={baseUrl}/login/oauth2/code/google-admin

# Registration para CLIENT
spring.security.oauth2.client.registration.google-client.client-id=${GOOGLE_CLIENT_ID}
spring.security.oauth2.client.registration.google-client.client-secret=${GOOGLE_CLIENT_SECRET}
spring.security.oauth2.client.registration.google-client.scope=openid,email,profile
spring.security.oauth2.client.registration.google-client.provider=google
spring.security.oauth2.client.registration.google-client.redirect-uri={baseUrl}/login/oauth2/code/google-client