spring.datasource.url=jdbc:postgresql://localhost:5432/postgres
spring.datasource.username=postgres
spring.datasource.password=Mj200512
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.data.web.pageable.serialization-mode=via_dto
spring.jpa.properties.hibernate.default_batch_fetch_size=20

spring.ai.google.genai.api-key=AIzaSyAf0bU0LcaYlJ8dc7mvqv7l5iLwbqTaGHI

spring.servlet.multipart.max-file-size=2MB
spring.servlet.multipart.max-request-size=10MB